import Head from 'next/head'

import { About, Experience, Hero, Navbar, Tech, Works } from '@/components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative z-0 bg-primary">
        <header>
          <Navbar />
        </header>
        <main>
          <Hero />
          <About />
          <Experience />
          <Tech />
          <Works />
          {/* <Feedbacks /> */}
          <div className="relative z-0">
            {/* <Contact /> */}
            {/* <StarsCanvas /> */}
          </div>
        </main>
      </div>
    </>
  )
}
